### ISSUE TITLE
can't get completed blob data when use onReceiveAudioBlob function

### ISSUE THREAD

**Issue by jeremylu007** [Haojen/npm-audio-recorder#1]
Hi,

I always get zero size blob data when I use `onReceiveAudioBlob` function.

Then I checked the source, and fond this place need `type` param
https://github.com/Haojen/npm-audio-recorder/blob/1146582f43635318cbce99a240d9c27cb90a28b7/worker.js#L88-L90

but there is no `type` argument when send command
https://github.com/Haojen/npm-audio-recorder/blob/1146582f43635318cbce99a240d9c27cb90a28b7/index.js#L88-L90

@Haojen , you fix this, or I send a MR?

**Comment by Haojen** [comment]
@Jeremy-lu  THX, I will fix that

**Comment by Haojen** [comment]
@Jeremy-lu  It's fixed. Try it  😃
