### ISSUE TITLE
针对recorder实例初始化的疑惑

### ISSUE THREAD

**Issue by jeremylu007** [Haojen/npm-audio-recorder#2]
https://github.com/Haojen/npm-audio-recorder/blob/fc45ff4aeef2bc57d39dc6068929e73a25203c5f/index.js#L34-L37

浩珍，为什么recorder实例要在startRecord的时候才初始化？而且，如果这样，后期每次执行startRecord都需要重新被初始化？

**Comment by Haojen** [comment]
@Jeremy-lu  thx！ 😄
